Repository finnlabs/openproject-backlogs, pull requests merged in 2018-07, with the labels that each got.

#269 don't use inline js to adhere to csp
  app/assets/javascripts/backlogs/taskboard.js
  app/helpers/rb_master_backlogs_helper.rb
Labels: bugfix, needs-review

#267 new demo data
  lib/open_project/backlogs/patches/project_seeder_patch.rb
Labels: feature, needs-review

#270 Fix/burndown chart
  app/assets/javascripts/backlogs/backlog.js
  app/assets/javascripts/backlogs/burndown.js
  app/assets/javascripts/backlogs/taskboard.js
  app/controllers/rb_burndown_charts_controller.rb
  app/views/rb_burndown_charts/_burndown.html.erb
  app/views/rb_burndown_charts/show.html.erb
  app/views/shared/_backlogs_header.html.erb
  features/team_member.feature
  spec/views/rb_burndown_charts/show_spec.rb
  vendor/assets/javascripts/backlogs/jquery.flot/jquery.flot.pie.js
Labels: bugfix

#271 [27318] Display "Shared" / "Inherited" icon again in front of versions from other projects
  app/views/project_settings/_versions.html.erb
Labels: bugfix
